# Generated by Django 4.0.5 on 2022-06-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField()),
                ('surnames', models.TextField()),
                ('age', models.TextField()),
            ],
        ),
    ]
