# Generated by Django 4.0.5 on 2022-06-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFamiliar', models.BooleanField(default=False)),
                ('fullname', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
